name = "sync-server"
main = "src/index.js"
compatibility_date = "2025-05-31"

[[durable_objects]]
name = "Aavdk"
class_name = "MyDurableObject"

[[d1_databases]]
binding = "checkersdb"
database_name = "checkers-db"

[[kv_namespaces]]
binding = "INVITES"
id = "a32e202fea9e402b8b0557d6d73321d5"
