name = "checkers-game"
main = "server/index.js"
compatibility_date = "2024-06-01"
workers_dev = true

# Durable Object bindings
[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[durable_objects.bindings]]
name = "SYNC"
class_name = "Sync"

[[durable_objects.bindings]]
name = "SPECTATOR"
class_name = "Spectator"

[[migrations]]
tag = "v1"
new_classes = [ "Room", "Sync", "Spectator" ]

# KV binding (used for invite tokens, etc.)
[[kv_namespaces]]
binding = "INVITES"
id = "a32e202fea9e402b8b0557d6d73321d5"  # Replace with your actual KV namespace ID

# D1 binding (used for storing player data, game state, etc.)
[[d1_databases]]
binding = "DB"
database_name = "checkers-db"
database_id = "d585fdfe-5228-4ad4-9edd-17645740c9d5"  # Replace with your actual D1 database ID

# Build options
[build]
command = "npm install"

# Dev environment config
[dev]
port = 8787
local_protocol = "http"
ip = "127.0.0.1"
