name = "sync-server"
main = "src/index.js"
compatibility_date = "2025-05-31"

[[durable_objects]]
name = "MY_DO_NAMESPACE"
class_name = "MyDurableObject"

[[d1_databases]]
binding = "MY_D1"
database_name = "my_database"

[[kv_namespaces]]
binding = "MY_KV"
id = "<your-kv-namespace-id>"