name = "checkers-game"
main = "index.js"
compatibility_date = "2024-06-01"

# Optional: if you’re using Durable Objects, KV, or D1
# Uncomment and edit these sections as needed!

# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxx"

# [[durable_objects]]
# name = "MY_DO"
# class_name = "MyDurableObject"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "xxxx"

# If you have environment-specific settings
[env.production]
zone_id = "0eed3778cd8a6233bc5f6b2f4af96185"
route = "https://multiplayercheckers.online/*"
